<?php

include_once('ca_job_listing.features.inc');

/**
 * Implementation of hook_menu().
 */
function ca_job_listing_menu() {
  $items['admin/settings/ca_job_listing'] = array(
    'title' => 'CA Job Listing: Admin',
    'description' => 'Change the look and feel of the ca_job_listing module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_job_listing_admin_settings_form'),
    'access arguments' => array('ca_job_listing change templates'),
    'file' => 'ca_job_listing.admin.inc',
    'file path' => drupal_get_path('module', 'ca_job_listing') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
  

/**
 * Implementation of hook_nodeapi().
 */
function ca_job_listing_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'job_listing') {
    switch ($op) {
      case 'presave':
        global $user;
        if ($user->uid == 1) {
          break;
        }
        if (!in_array('job_listing administrator', $user->roles) && !in_array('job lister', $user->roles)) {
          ca_job_listing_actions($node, $user);
          break;
        }
        break;
    }
  }
}

function ca_job_listing_action_info() {
  return array(
    'ca_job_listing_add_job_listing_admin_action' => array(
      'type' => 'user',
      'description' => t('Add job listing admin role'),
    ),
    'ca_job_listing_remove_job_listing_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove job listing admin role'),
    ),
    'ca_job_listing_add_job_lister_action' => array(
      'type' => 'user',
      'description' => t('Add job lister role'),
    ),
    'ca_job_listing_remove_job_lister_action' => array(
      'type' => 'user',
      'description' => t('Remove job lister role'),
    ),
  );
}

function ca_job_listing_add_job_listing_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'job listing admin') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_job_listing_add_job_listing_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Job Listing Administrator',
  );
  return $form;
}

function ca_job_listing_add_job_listing_admin_action_submit(&$form, &$form_state) {
  
}

function ca_job_listing_remove_job_listing_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'job listing admin') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_job_listing_remove_job_listing_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Job Listing Administrator',
  );
  return $form;
}

function ca_job_listing_remove_job_listing_admin_action_submit(&$form, &$form_state) {
  
}

function ca_job_listing_add_job_lister_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'job lister') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_job_listing_add_job_lister_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Job Lister',
  );
  return $form;
}

function ca_job_listing_add_job_lister_action_submit(&$form, &$form_state) {
  
}

function ca_job_listing_remove_job_lister_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'job lister') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_job_listing_remove_job_lister_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Job Lister',
  );
  return $form;
}

function ca_job_listing_remove_job_lister_action_submit(&$form, &$form_state) {
  
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_job_listing_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_job_listing_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_job_listing' || $subtask['name'] == 'home' || $task['name'] == 'node_view' || $task['name'] == 'term_view') {
    drupal_add_css(drupal_get_path('module', 'ca_job_listing') . "/css/ca_job_listing.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_job_listing_views_pre_render(&$view) {
  if ($view->name == 'job_listing') {
    drupal_add_css(drupal_get_path('module', 'ca_job_listing') . "/css/ca_job_listing.css", 'module', 'all', FALSE);
  }
}
